# Generated by Django 2.1.5 on 2019-04-10 22:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opioids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.TextField()),
                ('isOpioid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Overdoses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('abbrev', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescribers',
            fields=[
                ('doctorID', models.IntegerField(primary_key=True, serialize=False)),
                ('fName', models.TextField()),
                ('lName', models.TextField()),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Unknown')], default='O', max_length=1)),
                ('state', models.TextField(max_length=2)),
                ('credentials', models.TextField(null=True)),
                ('specialty', models.TextField()),
                ('opioid_prescriber', models.IntegerField()),
                ('totalPrescriptions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], db_index=True, default='A')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('reorder_trigger', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.DateTimeField(default=None, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('charge_id', models.TextField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.Sale')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Prescribers')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Opioids')),
            ],
        ),
    ]
