# Generated by Django 2.1.5 on 2019-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], db_index=True, default='A'),
        ),
    ]
