# Generated by Django 2.1.5 on 2019-04-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190318_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opioids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.TextField()),
                ('isOpioid', models.TextField(choices=[('1', 'Yes'), ('0', 'No')], db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overdoses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('abbrev', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorID', models.IntegerField()),
                ('fName', models.TextField()),
                ('lName', models.TextField()),
                ('gender', models.TextField(max_length=1)),
                ('state', models.TextField(max_length=2)),
                ('credentials', models.TextField()),
                ('specialty', models.TextField()),
                ('opioid_prescriber', models.IntegerField()),
                ('totalPrescriptions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.TextField()),
                ('qty', models.IntegerField()),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Prescribers')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], db_index=True, default='A'),
        ),
    ]
