# Generated by Django 2.1.5 on 2019-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190408_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opioids',
            name='isOpioid',
            field=models.TextField(choices=[('0', 'No'), ('1', 'Yes')], db_index=True),
        ),
        migrations.AlterField(
            model_name='prescribers',
            name='credentials',
            field=models.TextField(null=True),
        ),
    ]
