# Generated by Django 2.1.5 on 2019-04-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190408_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opioids',
            name='isOpioid',
            field=models.TextField(choices=[('1', 'Yes'), ('0', 'No')], db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], db_index=True, default='A'),
        ),
    ]
