# Generated by Django 2.1.5 on 2019-04-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190408_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opioids',
            name='isOpioid',
            field=models.TextField(),
        ),
    ]
